# Generated by Django 4.2.4 on 2023-12-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='人件費予算(超過分)')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部署名')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='従業員名')),
                ('number', models.IntegerField(verbose_name='従業員番号')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kintai.department', verbose_name='部署名')),
            ],
        ),
        migrations.CreateModel(
            name='Overtimetarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TimeField(default='0:00:00', verbose_name='目標残業時間')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='役職名')),
            ],
        ),
        migrations.CreateModel(
            name='KintaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(verbose_name='出勤時刻')),
                ('checkout', models.DateTimeField(verbose_name='退勤時刻')),
                ('overtime', models.TimeField(default='0:00:00', verbose_name='残業時間')),
                ('hourlypaycheck', models.IntegerField(verbose_name='時給(残業時)')),
                ('reasonforabsense', models.CharField(blank=True, max_length=50, verbose_name='欠勤理由')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kintai.employee', verbose_name='従業員')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kintai.position', verbose_name='役職名'),
        ),
    ]
