# Generated by Django 4.2.7 on 2023-12-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='従業員名')),
                ('number', models.IntegerField(verbose_name='従業員番号')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='役職名')),
            ],
        ),
        migrations.RemoveField(
            model_name='kintaimodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='kintaimodel',
            name='number',
        ),
        migrations.AlterField(
            model_name='kintaimodel',
            name='hourlypaycheck',
            field=models.IntegerField(verbose_name='時給(残業時)'),
        ),
        migrations.AlterField(
            model_name='kintaimodel',
            name='overtime',
            field=models.TimeField(default='0:00:00', verbose_name='残業時間'),
        ),
        migrations.AlterField(
            model_name='kintaimodel',
            name='paycheck',
            field=models.IntegerField(verbose_name='超過給料'),
        ),
        migrations.AddField(
            model_name='kintaimodel',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kintai.employee', verbose_name='従業員'),
        ),
        migrations.AlterField(
            model_name='kintaimodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kintai.position', verbose_name='役職名'),
        ),
    ]
