# Generated by Django 4.2.7 on 2023-12-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0005_rename_paycheck_kintaimodel_overpaycheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtimetarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TimeField(default='0:00:00', verbose_name='目標残業時間')),
            ],
        ),
    ]
